'use client';

import { useState } from 'react';
import { CreditCard, Clock, CheckCircle, XCircle, Copy, Download, ExternalLink } from 'lucide-react';
import toast from 'react-hot-toast';

export default function PaymentLinksPage() {
  const [activeTab, setActiveTab] = useState<'active' | 'paid' | 'expired'>('active');

  // Mock data
  const paymentLinks = [
    {
      id: 'PL001',
      orderId: 'ORD-2024-001',
      supplier: 'TechLight Industries',
      amount: 62500,
      currency: 'INR',
      status: 'active',
      createdAt: '2024-11-05',
      expiresAt: '2024-11-12',
      link: 'https://airavat.com/pay/abc123xyz',
      description: 'Industrial LED Lights (50 units)',
    },
    {
      id: 'PL002',
      orderId: 'ORD-2024-002',
      supplier: 'Textile Hub',
      amount: 140000,
      currency: 'INR',
      status: 'paid',
      createdAt: '2024-11-01',
      paidAt: '2024-11-02',
      link: 'https://airavat.com/pay/def456uvw',
      description: 'Cotton Fabric Rolls (500 meters)',
    },
    {
      id: 'PL003',
      orderId: 'ORD-2024-003',
      supplier: 'Organic Farms Co',
      amount: 45000,
      currency: 'INR',
      status: 'expired',
      createdAt: '2024-10-20',
      expiresAt: '2024-10-27',
      link: 'https://airavat.com/pay/ghi789rst',
      description: 'Organic Turmeric Powder (100 kg)',
    },
  ];

  const filteredLinks = paymentLinks.filter(link => link.status === activeTab);

  const copyToClipboard = (link: string) => {
    navigator.clipboard.writeText(link);
    toast.success('Payment link copied to clipboard!');
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'active':
        return <span className="badge badge-info">Active</span>;
      case 'paid':
        return <span className="badge badge-success">Paid</span>;
      case 'expired':
        return <span className="badge badge-warning">Expired</span>;
      default:
        return null;
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'active':
        return <Clock className="text-blue-500" size={24} />;
      case 'paid':
        return <CheckCircle className="text-green-500" size={24} />;
      case 'expired':
        return <XCircle className="text-yellow-500" size={24} />;
      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-regal-blue-800 mb-2">Payment Links</h1>
          <p className="text-gray-600">Manage your specialized payment links generated by suppliers</p>
        </div>

        {/* Stats Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-white rounded-xl shadow-md p-6">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-gray-600">Active Links</h3>
              <Clock className="text-blue-500" size={24} />
            </div>
            <p className="text-3xl font-bold text-regal-blue-700">
              {paymentLinks.filter(l => l.status === 'active').length}
            </p>
          </div>
          <div className="bg-white rounded-xl shadow-md p-6">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-gray-600">Paid</h3>
              <CheckCircle className="text-green-500" size={24} />
            </div>
            <p className="text-3xl font-bold text-green-600">
              {paymentLinks.filter(l => l.status === 'paid').length}
            </p>
          </div>
          <div className="bg-white rounded-xl shadow-md p-6">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-gray-600">Total Amount</h3>
              <CreditCard className="text-regal-gold-500" size={24} />
            </div>
            <p className="text-3xl font-bold text-regal-blue-700">
              ₹{paymentLinks.reduce((acc, l) => acc + l.amount, 0).toLocaleString()}
            </p>
          </div>
        </div>

        {/* Tabs */}
        <div className="bg-white rounded-xl shadow-md mb-6">
          <div className="flex border-b">
            <button
              onClick={() => setActiveTab('active')}
              className={`flex-1 px-6 py-4 font-semibold transition ${
                activeTab === 'active'
                  ? 'text-teal-600 border-b-2 border-teal-600'
                  : 'text-gray-600 hover:text-gray-800'
              }`}
            >
              Active ({paymentLinks.filter(l => l.status === 'active').length})
            </button>
            <button
              onClick={() => setActiveTab('paid')}
              className={`flex-1 px-6 py-4 font-semibold transition ${
                activeTab === 'paid'
                  ? 'text-teal-600 border-b-2 border-teal-600'
                  : 'text-gray-600 hover:text-gray-800'
              }`}
            >
              Paid ({paymentLinks.filter(l => l.status === 'paid').length})
            </button>
            <button
              onClick={() => setActiveTab('expired')}
              className={`flex-1 px-6 py-4 font-semibold transition ${
                activeTab === 'expired'
                  ? 'text-teal-600 border-b-2 border-teal-600'
                  : 'text-gray-600 hover:text-gray-800'
              }`}
            >
              Expired ({paymentLinks.filter(l => l.status === 'expired').length})
            </button>
          </div>
        </div>

        {/* Payment Links List */}
        <div className="space-y-4">
          {filteredLinks.map((link) => (
            <div key={link.id} className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition">
              <div className="flex flex-col lg:flex-row lg:items-center gap-4">
                {/* Status Icon */}
                <div className="flex-shrink-0">
                  {getStatusIcon(link.status)}
                </div>

                {/* Main Info */}
                <div className="flex-1">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <h3 className="text-xl font-semibold text-gray-800">{link.description}</h3>
                      <p className="text-gray-600">{link.supplier}</p>
                    </div>
                    {getStatusBadge(link.status)}
                  </div>

                  <div className="grid md:grid-cols-2 gap-4 mt-3">
                    <div>
                      <p className="text-sm text-gray-500">Payment Link ID</p>
                      <p className="font-medium">{link.id}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Order ID</p>
                      <p className="font-medium">{link.orderId}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Amount</p>
                      <p className="font-bold text-2xl text-regal-blue-700">
                        ₹{link.amount.toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">
                        {link.status === 'paid' ? 'Paid On' : link.status === 'expired' ? 'Expired On' : 'Expires On'}
                      </p>
                      <p className="font-medium">
                        {link.status === 'paid' ? link.paidAt : link.expiresAt}
                      </p>
                    </div>
                  </div>

                  {/* Link Display */}
                  {link.status === 'active' && (
                    <div className="mt-4 flex items-center gap-2 p-3 bg-gray-50 rounded-lg">
                      <code className="flex-1 text-sm text-gray-700 truncate">{link.link}</code>
                      <button
                        onClick={() => copyToClipboard(link.link)}
                        className="p-2 hover:bg-gray-200 rounded transition"
                        title="Copy link"
                      >
                        <Copy size={18} className="text-gray-600" />
                      </button>
                    </div>
                  )}
                </div>

                {/* Actions */}
                <div className="flex lg:flex-col gap-2">
                  {link.status === 'active' && (
                    <button className="btn-primary flex items-center gap-2">
                      <ExternalLink size={18} />
                      Pay Now
                    </button>
                  )}
                  <button className="border border-gray-300 px-4 py-2 rounded-lg font-medium hover:bg-gray-50 transition flex items-center gap-2">
                    <Download size={18} />
                    Invoice
                  </button>
                </div>
              </div>
            </div>
          ))}

          {filteredLinks.length === 0 && (
            <div className="text-center py-12">
              <CreditCard className="mx-auto text-gray-400 mb-4" size={64} />
              <h3 className="text-xl font-semibold text-gray-600 mb-2">
                No {activeTab} payment links
              </h3>
              <p className="text-gray-500">
                Payment links will appear here once suppliers generate them
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
